Repository BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team4, pull requests merged in 2023-04, with the labels that each got.

#86 Feature#71 only the user can edit and delete their own coupons
  app/assets/stylesheets/pages/_main.scss
  app/views/mainpages/_content.html.erb
Labels: Ever

#100 Fix logout
  app/views/mainpages/_content.html.erb
Labels: Ever

#102 Show all users
  app/controllers/mainpages_controller.rb
  app/views/mainpages/_content.html.erb
  app/views/mainpages/index.html.erb
  app/views/share/_menu.html.erb
Labels: Ever

#92 Show user coupons, when user card is clicked.
  app/assets/stylesheets/pages/_main.scss
  app/controllers/mainpages_controller.rb
  app/views/mainpages/_content.html.erb
  app/views/mainpages/_home.html.erb
Labels: Ever

#103 Fix responsive search bar
  app/assets/stylesheets/pages/_main.scss
Labels: Ever

#106 redesign coupon cards added
  app/assets/stylesheets/pages/_main.scss
  app/assets/stylesheets/pages/_showCupons.scss
  app/views/mainpages/_content.html.erb
Labels: In review, Ever

#105 config example for deploy
  .gitignore
  railwayEnv.txt.example
Labels: Ever

#108 Fix responsive lateral menu
  app/assets/stylesheets/pages/_main.scss
  app/javascript/navbarService.js
Labels: Ever

#124 Limit characters category
  app/assets/stylesheets/pages/_main.scss
  app/javascript/navbarService.js
  app/views/categories/_form.html.erb
  app/views/share/_menu.html.erb
Labels: Ewar

#116 Admin can delete users
  app/assets/stylesheets/pages/_main.scss
  app/controllers/mainpages_controller.rb
  app/views/mainpages/_content.html.erb
  config/routes.rb
Labels: Ewar

#118 Feature#114 pagination main page
  app/controllers/cupons_controller.rb
  app/controllers/mainpages_controller.rb
  app/views/mainpages/index.html.erb
  config/initializers/pagy.rb
Labels: Ewar

#121 edit and delete user counts
  app/assets/config/manifest.js
  app/assets/images/engranaje.png
  app/assets/javascripts/show.js
  app/assets/javascripts/update.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/pages/_edit.scss
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/utilities/_variables.scss
  app/controllers/cupons_controller.rb
  app/controllers/mainpages_controller.rb
  app/controllers/registrations_controller.rb
  app/javascript/application.js
  app/javascript/modalAlert.js
  app/javascript/modalClose.js
  app/javascript/modal_controller.js
  app/models/user.rb
  app/views/cupons/show.html.erb
  app/views/devise/registrations/_edit.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/layouts/application.html.erb
  app/views/mainpages/_home.html.erb
  app/views/mainpages/index.html.erb
  config/database.yml.example
  config/routes.rb
Labels: In review

#133 Feature#122 add scroll to login
  app/assets/stylesheets/pages/_users.scss
Labels: oscar

#139 finish responsive view new category
  app/assets/stylesheets/pages/_categories.scss
  app/views/categories/new.html.erb
Labels: oscar

#148 carousel view only in root_path
  app/views/mainpages/index.html.erb
Labels: In review, oscar

#144 Delete cuopons with 10 dislikes function added
  app/assets/stylesheets/pages/_main.scss
  app/assets/stylesheets/utilities/_variables.scss
  app/controllers/cupons_controller.rb
  app/models/cupon.rb
  app/models/vote.rb
  app/views/layouts/application.html.erb
  app/views/mainpages/index.html.erb
  db/migrate/20230418012415_create_votes.rb
  db/schema.rb
  db/seeds.rb
Labels: In review, oscar

#150 overlay in edit coupon view fixed
  app/views/cupons/edit.html.erb
Labels: In review, oscar

#151 Feature#136 update readme
  README.md
Labels: oscar
