Repository BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team4, pull requests merged in 2023-03, with the labels that each got.

#34 Feature#27 navigation bar
  app/assets/images/arrow.svg
  app/assets/images/categories.svg
  app/assets/images/home.svg
  app/assets/images/logo02.png
  app/assets/images/recientes.svg
  app/assets/stylesheets/pages/_main.scss
  app/assets/stylesheets/utilities/_mixins.scss
  app/views/layouts/application.html.erb
  app/views/mainpages/_menu.html.erb
  app/views/mainpages/index.html.erb
Labels: Ever

#41 Show user coupons/promotion functionality added
  app/assets/images/coupon_defaul.webp
  app/assets/stylesheets/pages/_main.scss
  app/assets/stylesheets/utilities/_variables.scss
  app/controllers/cupons_controller.rb
  app/controllers/mainpages_controller.rb
  app/views/mainpages/_content.html.erb
  app/views/share/_header.html.erb
  db/seeds.rb
Labels: In review, Ewar

#45 Feature#38 register category
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/pages/_categories.scss
  app/assets/stylesheets/pages/_main.scss
  app/assets/stylesheets/utilities/_variables.scss
  app/controllers/categories_controller.rb
  app/views/categories/_category.html.erb
  app/views/categories/_category.json.jbuilder
  app/views/categories/_form.html.erb
  app/views/categories/edit.html.erb
  app/views/categories/index.html.erb
  app/views/categories/index.json.jbuilder
  app/views/categories/new.html.erb
  app/views/layouts/application.html.erb
  app/views/mainpages/_category.html.erb
  config/routes.rb
  db/migrate/20230315224711_create_categories.rb
  db/schema.rb
  test/controllers/categories_controller_test.rb
  test/fixtures/categories.yml
  test/system/categories_test.rb
Labels: Ewar

#46 coupon/offer carousel added
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/pages/_main.scss
  app/assets/stylesheets/utilities/_variables.scss
  app/views/mainpages/_carousel.html.erb
  app/views/mainpages/index.html.erb
  db/seeds.rb
Labels: In review, oscar

#57 Added coupon map view
  app/assets/stylesheets/pages/_showCupons.scss
  app/controllers/cupons_controller.rb
  app/models/cupon.rb
  app/views/cupons/new.html.erb
  app/views/cupons/show.html.erb
Labels: In review, oscar

#58 finish the hidden menu left
  app/assets/config/manifest.js
  app/assets/images/menuburger.svg
  app/assets/stylesheets/pages/_main.scss
  app/javascript/navbarService.js
  app/views/share/_menu.html.erb
Labels: oscar

#59 Feature#44 add functionality to search bar
  app/assets/images/user.png
  app/assets/stylesheets/pages/_cupons.scss
  app/assets/stylesheets/pages/_main.scss
  app/controllers/mainpages_controller.rb
  app/models/cupon.rb
  app/models/user.rb
  app/views/cupons/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/mainpages/_carousel.html.erb
  app/views/mainpages/_content.html.erb
  app/views/share/_header.html.erb
  config/routes.rb
Labels: In review, oscar

#61 Add category to the form of add coupon
  app/controllers/cupons_controller.rb
  app/views/cupons/new.html.erb
  db/migrate/20230322223757_add_category_id_to_cupons.rb
  db/schema.rb
Labels: oscar

#62 Feature#48 add functionality to action show coupon detail
  app/controllers/cupons_controller.rb
  app/views/cupons/show.html.erb
  app/views/mainpages/_content.html.erb
Labels: oscar

#56 Expired coupons
  app/controllers/cupons_controller.rb
Labels: In review, oscar

#78 Render the offer link in the show view
  app/assets/stylesheets/pages/_showCupons.scss
  app/views/cupons/show.html.erb
Labels: Diego

#65 style and funtionality like/dislike added
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/images/dislike.svg
  app/assets/images/heart.svg
  app/assets/images/like.svg
  app/assets/javascripts/reload.js
  app/assets/javascripts/show.js
  app/assets/javascripts/update.js
  app/assets/stylesheets/pages/_showCupons.scss
  app/assets/stylesheets/utilities/_variables.scss
  app/controllers/cupons_controller.rb
  app/javascript/application.js
  app/views/cupons/show.html.erb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/routes.rb
Labels: In review, oscar

#76 Return Button in Category view
  app/assets/stylesheets/pages/_categories.scss
  app/views/categories/index.html.erb
Labels: Diego

#83 fix recharge coupon view bug many times
  app/assets/javascripts/reload.js
  app/assets/javascripts/show.js
  app/controllers/cupons_controller.rb
  app/views/cupons/show.html.erb
  db/schema.rb
Labels: In review, Diego

#87 Added a nice design to the user card.
  app/assets/stylesheets/pages/_main.scss
  app/views/mainpages/_content.html.erb
Labels: Diego

#89 best punctuation coupons in the carousel and different accounts' likes and dislikes.
  app/assets/config/manifest.js
  app/assets/javascripts/cookies.js
  app/assets/stylesheets/pages/_main.scss
  app/assets/stylesheets/pages/_showCupons.scss
  app/controllers/mainpages_controller.rb
  app/controllers/registrations_controller.rb
  app/javascript/application.js
  app/models/cupon.rb
  app/views/layouts/application.html.erb
  app/views/mainpages/_carousel.html.erb
  app/views/share/_header.html.erb
  config/routes.rb
Labels: In review, Diego
